lib/views/games.py
import os
import requests
import json
from bs4 import BeautifulSoup
from flask import (
    Flask, flash, render_template, Blueprint,
    redirect, request, session, url_for)
from flask_pymongo import PyMongo
from bson.objectid import ObjectId
from lib.helper import db
if os.path.exists("env.py"):
    import env

blueprint = Blueprint("games", __name__, url_prefix="/games")
API_KEY = os.environ.get("API_KEY")


def insert_review():
    '''adds review into db'''
    review = {
            "game_name": request.form.get("game_name"),
            "game_id": request.form.get("game_id"),
            "game_rating": request.form.get("rating"),
            "game_img": request.form.get("game_img"),
            "user": session["user"],
            "game_review": request.form.get("review")
        }
    db().reviews.insert_one(review)


def check_review_exists():
    '''checks if user reviewed already'''
    already_reviewed = {
            "game_name": request.form.get("game_name"),
            "user": session["user"]
        }
    return db().reviews.find_one(already_reviewed)


def edit_review_data():
    '''data for editing review'''
    edit = {
            "game_name": request.form.get("game_name"),
            "game_rating": request.form.get("rating"),
            "game_img": request.form.get("game_img"),
            "user": session["user"],
            "game_review": request.form.get("review")
        }
    return edit


@blueprint.route("/")
def get_games():
    '''requests game data from api'''
    parameters = {
        "page_size": 8
    }
    try:
        response = requests.get(
            f"https://api.rawg.io/api/games?key={API_KEY}", params=parameters)
        data = response.json()
    except requests.exceptions.RequestException as request_exception:
        raise SystemExit from request_exception

    return render_template("games.html", data=data)


@blueprint.route("/search", methods=["GET", "POST"])
def search():
    '''Allows user to search games using the rawg API as the database'''
    query = request.form.get("query")
    parameters = {
        "page_size": 8,
        "search": query
    }
    try:
        response = requests.get(
            f"https://api.rawg.io/api/games?key={API_KEY}", params=parameters)
        data = response.json()
    except requests.exceptions.RequestException as request_exception:
        raise SystemExit from request_exception

    return render_template("games.html", data=data)


@blueprint.route("/<game_id>")
def game(game_id):
    '''gets individual game information'''
    try:
        response = requests.get(
            f"https://api.rawg.io/api/games/{game_id}?key={API_KEY}")
        game = response.json()
    except requests.exceptions.RequestException as request_exception:
        raise SystemExit from request_exception

    total = 0
    game_id = str(game['id'])
    reviews = db().reviews.find(
        {'game_id': game_id}, {'_id': 0, 'game_rating': 1})
    count = reviews.count()
    for review in reviews:
        total += int(review['game_rating'])
    average = round(total / count, 1)
    print(average)

    htmlDescription = json.dumps(game['description'])
    soup = BeautifulSoup(htmlDescription, 'html.parser')
    description = soup.get_text()

    # doesn't work
    # clean = description.replace("\n", "")

    return render_template(
        "game.html", game=game, description=description, average=average)


@blueprint.route("/get_reviews")
def get_reviews():
    '''Shows list of reviews from Mongodb'''
    reviews = db().reviews.find()
    return render_template("reviews.html", reviews=reviews)


@blueprint.route("/search_reviews", methods=["GET", "POST"])
def search_reviews():
    '''Searches through user reviews'''
    query = request.form.get("query")
    reviews = list(db().reviews.find({"$text": {"$search": query}}))
    if not reviews:
        flash("Couldn't find any reviews to match your search", "error-msg")
    return render_template("reviews.html", reviews=reviews)


@blueprint.route("/add_review", methods=["GET", "POST"])
def add_review():
    '''adds review to db'''
    if request.method == "POST":
        if check_review_exists() is None:
            insert_review()
            flash("Review added successfully", "success-msg")
            return redirect(url_for("games.get_reviews"))

        flash("You've Already reviewed this game", "error-msg")
    return redirect(url_for("games.get_reviews"))


@blueprint.route("/edit_review/<review_id>", methods=["GET", "POST"])
def edit_review(review_id):
    '''Finds review by id and edits it'''
    review = db().reviews.find_one({"_id": ObjectId(review_id)})
    if request.method == "POST":
        db().reviews.update({"_id": ObjectId(review_id)}, edit_review_data())
        flash("Review updated successfully", "success-msg")
        return redirect(url_for("games.get_reviews"))

    return render_template("edit_review.html", review=review)


@blueprint.route("/delete_review/<review_id>")
def delete_review(review_id):
    '''Deletes Review by id'''
    db().reviews.delete_one({"_id": ObjectId(review_id)})
    flash("Review deleted successfully", "success-msg")
    return redirect(url_for("games.get_reviews"))

lib/views/user.py
import os
from flask import (
    Flask, flash, render_template, Blueprint,
    redirect, request, session, url_for)
from flask_pymongo import PyMongo
from werkzeug.security import generate_password_hash, check_password_hash
from lib.helper import db
if os.path.exists("env.py"):
    import env

blueprint = Blueprint("user", __name__, url_prefix="/user")


def existing_user():
    '''checks username against database'''
    return db().users.find_one(
            {"username": request.form.get("username").lower()})


def insert_new_user():
    '''Registers new user'''
    new_user = {
                "username": request.form.get("username").lower(),
                "password": generate_password_hash(
                    request.form.get("password"))
        }
    db().users.insert_one(new_user)


def update_password():
    '''changes users password'''
    return db().users.update_one(
                    {"username": session["user"]},
                    {"$set": {"password": generate_password_hash(
                        request.form.get("newPassword"))}}
                )


@blueprint.route("/register", methods=["GET", "POST"])
def register():
    '''Checks if password matches, if it does registers
     new user if they dont already exist'''
    if request.method == "POST":
        if request.form.get(
         "password") != request.form.get("confirm-password"):
            flash("Passwords don't match", 'error-msg')
            return render_template("register.html")
        # check if username exists
        if existing_user():
            flash("Username already exists", 'error-msg')
            return redirect(url_for("user.register"))
        # inserts new user into database
        insert_new_user()
        # put new user into 'session' cookie
        session["user"] = request.form.get("username").lower()
        flash("Registration Successful", 'success-msg')
        return redirect(url_for("user.profile", username=session["user"]))
    return render_template("register.html")


@blueprint.route("/signin", methods=["GET", "POST"])
def signin():
    '''Signs in user if username exists'''
    if request.method == "POST":
        # check if username exists
        if existing_user():
            # ensure hashed password matches
            if check_password_hash(
              existing_user()["password"], request.form.get("password")):
                session["user"] = request.form.get("username").lower()
                username = request.form.get("username")
                flash(f"Welcome, {username}", "success-msg")
                return redirect(url_for(
                    "user.profile", username=session["user"]))

        # username doesn't exist / Passwords wrong
        flash("Incorrect Username/Password", 'error-msg')
    return render_template("signin.html")


@blueprint.route("/profile/<username>", methods=["GET", "POST"])
def profile(username):
    '''gets session user's username from db'''
    username = db().users.find_one(
        {"username": session["user"]})["username"]
    reviews = db().reviews.find(
        {"user": session["user"]})
    return render_template(
        "profile.html", username=username, reviews=reviews)


@blueprint.route("/signout")
def signout():
    '''remove user from session cookie'''
    flash("You have been logged out", "success-msg")
    session.pop("user")
    return redirect(url_for("user.signin"))


@blueprint.route("/delete_profile")
def delete_profile():
    '''takes user to confirm if they want to delete profile'''
    return render_template("delete_profile.html")


@blueprint.route("/delete_user")
def delete_user():
    '''Deletes user's profile/account along with all reviews'''
    db().reviews.delete_many({"user": session["user"]})
    db().users.delete_one({"username": session["user"]})
    session.pop("user")

    flash("Account deleted successfully", "success-msg")
    return redirect(url_for("register"))


@blueprint.route("/change_password")
def change_password():
    '''takes user to change password form'''
    return render_template("change_password.html")


@blueprint.route("/new_password", methods=["GET", "POST"])
def new_password():
    '''Checks user's password and if it is lets them change it'''
    user = db().users.find_one({"username": session["user"]})
    password = request.form.get("newPassword")
    confirm_new_password = request.form.get("confirmNewPassword")
    if request.method == "POST":
        if password != confirm_new_password:
            flash("passwords don't match", "error-msg")
            return redirect(url_for("user.change_password"))
        if check_password_hash(
             user["password"], request.form.get("oldPassword")):
            update_password()
            flash("password updated", "success-msg")
            return redirect(url_for(
                 "user.profile", username=session["user"]))

lib/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"
        integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
        type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    {% block styles %}
    {% endblock %}
    <title>GAMEReview</title>
</head>

<body>
    <!--Main navigation bar-->
    <nav>
        <div class="nav-wrapper">
            <a href="{{ url_for('games.get_games') }}" class="brand-logo">
                <h1 class="brand-name"><span class="brand-name-game">GAME</span><span class="brand-name-review"><span
                            class="brand-name-r">R</span>eview</span></h1>
            </a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="fas fa-bars"></i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="{{ url_for('games.get_games') }}">Home</a></li>
                <li><a href="{{ url_for('games.get_reviews') }}">Reviews</a></li>
                {% if session.user %}
                <li><a href="{{ url_for('user.profile', username=session['user']) }}">Profile</a></li>
                <li><a href="{{ url_for('user.signout') }}">Sign out</a></li>
                {% else %}
                <li><a href="{{ url_for('user.register') }}">Register</a></li>
                <li><a href="{{ url_for('user.signin') }}">Sign in</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!--Mobile navigation side menu-->
    <ul class="sidenav" id="mobile-demo">
        <li><a href="{{ url_for('games.get_games') }}">Home</a></li>
        <li><a href="{{ url_for('games.get_reviews') }}">Reviews</a></li>
        {% if session.user %}
        <li><a href="{{ url_for('user.profile', username=session['user']) }}">Profile</a></li>
        <li><a href="{{ url_for('user.signout') }}">Sign out</a></li>
        {% else %}
        <li><a href="{{ url_for('user.register') }}">Register</a></li>
        <li><a href="{{ url_for('user.signin') }}">Sign in</a></li>
        {% endif %}
    </ul>

    <section>
        <!--- flash messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="row flashes">
            <h4 class="center-align {{ category }}">{{ message }}</h4>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </section>

    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    {% block scripts %}
    {% endblock %}
</body>

lib/templates/change_password.html
{% extends "base.html" %}
{% block content %}

<h3 class="center-align heading-white">Change Password</h3>

<div class="row">
    <form class="col s12 m8 offset-m2" method="POST" action="{{ url_for('user.new_password') }}">
        <div class="col s12 m10 offset-m1">
            <div class="card blue-grey darken-1 register-card">
                <div class="row">
                    <div class="input-field col s12">
                        <i class="fas fa-unlock-alt prefix"></i>
                        <input id="oldPassword" name="oldPassword" type="password" minlength="6" maxlength="18"
                            class="validate" pattern="^[a-zA-Z0-9]{6,18}$" required>
                        <label for="oldPassword">Old Password</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="fas fa-user-lock prefix"></i>
                        <input id="newPassword" name="newPassword" type="password" minlength="6" maxlength="18"
                            class="validate" pattern="^[a-zA-Z0-9]{6,18}$" required>
                        <label for="newPassword">New Password</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="fas fa-user-lock prefix"></i>
                        <input id="confirmNewPassword" name="confirmNewPassword" type="password" minlength="6"
                            maxlength="18" class="validate" pattern="^[a-zA-Z0-9]{6,18}$" required>
                        <label for="confirmNewPassword">Re-enter Password</label>
                    </div>
                </div>
                <div class="row">
                    <button type="submit" class="col s8 offset-s2 btn-large darken-4 text-shadow  teal accent-2">
                        Register <i class="fas fa-sign-in-alt"></i>
                    </button>
                    <div class="div s2"></div>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

lib/templates/delete_profile.html
{% extends "base.html" %}
{% block content %}

<h3 class="center-align heading-white">Delete Profile?</h3>

<div class="row">
    <div class="col s12 m10 offset-m1">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <p class="center-align">Are you sure you want to delete your profile?</p><br>
          <p class="center-align">All past reviews will be deleted...</p>
        </div>
        <div class="card-action center-align">
          <a class="waves-effect waves-light btn btn-yes" href="{{ url_for('user.delete_user') }}"><i class="fas fa-check"></i> Yes, I'm sure!</a>
          <a class="waves-effect red accent-2 btn btn-no" href="{{ url_for('games.get_games') }}">Take me back <i class="fas fa-times"></i></a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

lib/templates/edit_review.html
{% extends "base.html" %}
{% block content %}
<h4 class="center-align">Edit</h4>

<div class="row">
    <div class="col s12 offset-m1 m10">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <img class="game-img" src='{{ review.game_img }}' alt="{{ review.game_name }} cover art">
          <span class="card-title">{{ review.game_name }}</span>
          <span class="card-info"></span>
        </div>
        <div class="card-action collapsible edit-card">   
              <form method="POST" action="{{ url_for('games.edit_review', review_id=review._id) }}">
                <textarea onkeyup="textAreaUpdate(this)" minlength="30" maxlength="300" class="review-txt" placeholder="Write your review..." name="review" required>{{ review.game_review }}</textarea>
                <label for="rating">Rating (out of 10)</label>
                <select id="rating" name="rating" required>
                  <option value="" disabled selected>You last scored this game {{ review.game_rating }}</option>
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                  <option value="6">6</option>
                  <option value="7">7</option>
                  <option value="8">8</option>
                  <option value="9">9</option>
                  <option value="10">10</option>
                </select>
                <input type="text" class="hidden-input" name="game_img" value="{{ review.game_img }}">
                <input type="text" class="hidden-input" name="game_name" value="{{ review.game_name }}">
                <button class="review-btn" name="review" type="submit">
                  <i class="fas fa-pencil-alt"></i> Edit
                </button>
              </form>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

lib/templates/game.html
{% extends "base.html" %}
{% block content %}


<div class="row">
    <div class="col s12 m6">
        <div class="gameview-img-cntain teal">
            <img class="gameview-img" src='{{ game["background_image"] }}'
                    alt="{{ game['name'] }} cover art">
        </div>
        <div>{{ game['released'] }}</div>
        <div>{{ game['metacritic'] }}/100</div>
        <div>{{ game['reddit_url'] }}</div>
        <div>{{ game['reddit_logo'] }}/100</div>
    </div>
    <div class="col s12 m6">
        <div class="card-panel teal">
            <p>{{ description }}</p>
        </div>
    </div>
    <div class="col s12 m6">
        <div class="card-panel teal">
            {% for platform in game['platforms'] %}
            <p>{{ platform.platform.name }}</p>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %} 

lib/templates/games.html
{% extends "base.html" %}
{% block content %}

<div class="row card-panel search-bar">
  <form action="{{ url_for('games.search') }}" method="post" class="col s12">
    <div class="row valign-wrapper center-align">
      <div class="input-field col s9 offset-s1">
        <input type="text" name="query" id="query" minlength="3" class="validate" required>
        <label for="query">Search Games</label>
        <button type="submit" class="light-blue search-btn">
          <i class="fas fa-search"></i><br>
          search
        </button>
      </div>
    </div>
  </form>
</div>

{% for game in data['results'] %}
<div class="row">
  <div class="col s12 offset-m1 m10">
    <a href="{{ url_for('games.game', game_id=game['id']) }}"><div class="card game-card blue-grey darken-1">
      <div class="card-content white-text">
        <img class="game-img" src='{{ game["background_image"] }}' alt="{{ game['name'] }} cover art">
        <span class="card-title">{{ game['name'] }}</span>
        <div class="card-info released-title">Released: <span class="released-info">{{ game['released'] }}</span></div>
        {% for platform in game['platforms'] %}
        <span class="card-info platform-info {{ platform['platform']['name']|lower }}">{{ platform['platform']['name'] }}
        </span>
        {% endfor %}
      </div>
      <div class="buy-btn"><a href="https://www.amazon.co.uk/s?k={{ game['name']|replace(' ', '+') }}&i=videogames" target="_blank"
          rel="sponsored noopener">Buy now <i class="fas fa-store-alt"></i></a></div>
      <ul class="card-action collapsible">
        {% if session.user %}
        <li>
          <div class="collapsible-header card-collapsible-header">
            <p class="review-dropdwn">Review</p><br>
            <i class="fas fa-chevron-down review-arrow"></i>
          </div>
          <div class="collapsible-body">
            <form method="POST" action="{{ url_for('games.add_review') }}">
              <textarea onkeyup="textAreaUpdate(this)" minlength="30" maxlength="300" class="review-txt"
                placeholder="Write your review..." name="review" required></textarea>
              <label for="rating">Rating (out of 10)</label>
              <select id="rating" name="rating" required>
                <option value="" disabled selected>What's your rating?</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
              </select>
              <input type="text" class="hidden-input" name="game_img" value="{{ game['background_image'] }}">
              <input type="text" class="hidden-input" name="game_name" value="{{ game['name'] }}">
              <input type="text" class="hidden-input" name="game_id" value="{{ game['id'] }}">
              <button class="review-btn" name="review" type="submit">
                <i class="fas fa-pencil-alt"></i> Review
              </button>
            </form>
          </div>
        </li>
        {% endif %}
      </ul>
    </div></a>
  </div>
</div>
{% endfor %}

<footer>
  <p class="center-align">All data and images sourced from</p>
  <a href="https://rawg.io/" rel="noopener">
    <p class="center-align">rawg.io</p>
  </a>
</footer>

{% endblock %}

lib/templates/profile.html
{% extends "base.html" %}
{% block content %}

<div class="row">
    <div class="col s12 m8 offset-m2">
        <div class="card-panel">
            <h5 class="center-align">
                <i class="fas fa-user prefix"></i>
                {{ username }}'s Profile
            </h5>
            <div class="card-action center-align">
              <a class="profile-option" href="{{ url_for('user.delete_profile') }}">Delete Account</a><br>
              <a class="profile-option" href="{{ url_for('user.change_password') }}">Change Password</a><br>
            </div>
        </div>
    </div>
</div>

<h4 class="center-align heading-white">My Reviews</h4>
{% for review in reviews|reverse %}
<div class="row">
  <div class="col s12 offset-m1 m10">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <img class="game-img" src='{{ review.game_img }}' alt="img of {{ review.game_name }}">
        <span class="card-title">{{ review.game_name }}</span>
        <div class="rating-card-info">
          <p class="text-align">{{ review.game_rating }}</p>
        </div>
      </div>
      <ul class="card-action collapsible">
        <li>
          <div class="edit-btns">
            <a href="{{ url_for('games.edit_review', review_id=review._id) }}" class="waves-effect waves-light btn-small edit-btn">
              <i class="fas fa-pencil-alt"></i> Edit</a>
            <a href="{{ url_for('games.delete_review', review_id=review._id) }}"
              class="waves-effect red accent-2 btn-small delete-btn">Delete
              <i class="far fa-trash-alt"></i></a>
          </div>
          <div class="collapsible-header">
            <p class="review-dropdwn">Read</p><br>
            <i class="fas fa-chevron-down review-arrow"></i>
          </div>
          <div class="collapsible-body review-body">
            <article class="review-txt">
              <p>{{ review.game_review }}</p>
            </article>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
{% endfor %}


{% endblock %}

lib/templates/register.html
{% extends "base.html" %}
{% block content %}

<h3 class="center-align heading-white">Register</h3>

<div class="row">
    <form class="col s12 m8 offset-m2" method="POST" action="{{ url_for('user.register') }}">
        <div class="col s12 m10 offset-m1">
            <div class="card blue-grey darken-1 register-card">
                <div class="row">
                    <div class="input-field col s12">
                        <i class="fas fa-user-plus prefix"></i>
                        <input id="username" name="username" type="text" minlength="4" maxlength="18" class="validate"
                            pattern="^[a-zA-Z0-9]{4,18}$" required>
                        <label for="username">Username</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="fas fa-user-lock prefix"></i>
                        <input id="password" name="password" type="password" minlength="6" maxlength="18"
                            class="validate" pattern="^[a-zA-Z0-9]{6,18}$" required>
                        <label for="password">Password</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="fas fa-user-lock prefix"></i>
                        <input id="confirm-password" name="confirm-password" type="password" minlength="6"
                            maxlength="18" class="validate" pattern="^[a-zA-Z0-9]{6,18}$" required>
                        <label for="confirm-password">Re-enter Password</label>
                    </div>
                </div>
                <div class="row">
                    <button type="submit" class="col s8 offset-s2 btn-large darken-4 text-shadow  teal accent-2">
                        Register <i class="fas fa-sign-in-alt"></i>
                    </button>
                    <div class="div s2"></div>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="row">
    <div class="col-12">
        <p class="center-align">Already registered? <a href="{{ url_for('user.signin') }}">Sign in here</a></p>
    </div>
</div>

{% endblock %}

lib/templates/reviews.html
{% extends "base.html" %}
{% block content %}

<div class="row card-panel search-bar">
  <form action="{{ url_for('games.search_reviews') }}" method="post" class="col s12">
    <div class="row valign-wrapper center-align">
      <div class="input-field col s9 offset-s1">
        <input type="text" name="query" id="query" minlength="3" class="validate" required>
        <label for="query">Search Games</label>
        <button type="submit" class="light-blue search-btn">
          <i class="fas fa-search"></i><br>
          search
        </button>
      </div>
    </div>
  </form>    
</div>

{% for review in reviews|reverse %}
<div class="row">
  <div class="col s12 offset-m1 m10">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <img class="game-img" src='{{ review.game_img }}' alt="image of {{ review.game_name }}">
        <span class="card-title">{{ review.game_name }}</span>
        <span class="card-info reviewed-by">Reviewed By: {{ review.user }}</span>
        <div class="rating-card-info">
          <p class="text-align">{{ review.game_rating }}</p>
        </div>
      </div>
      <ul class="card-action collapsible">
        <li class="dropdwn">
          {% if session.user|lower == review.user|lower %}
          <div class="edit-btns">
            <a href="{{ url_for('games.edit_review', review_id=review._id) }}" class="waves-effect waves-light btn-small edit-btn">
              <i class="fas fa-pencil-alt"></i> Edit</a>
            <a href="{{ url_for('games.delete_review', review_id=review._id) }}"
              class="waves-effect red accent-2 btn-small delete-btn">Delete
              <i class="far fa-trash-alt"></i></a>
          </div>
          {% endif %}
          <div class="collapsible-header card-collapsible-header">
            <div class="dropdwn-btn dropdwn-btn-read">
              <p class="review-dropdwn">Read</p>
              <i class="fas fa-chevron-down review-arrow"></i>
            </div>
          </div>
          <div class="collapsible-body review-body">
            <article class="review-txt"> 
              <p>{{ review.game_review }}</p>
            </article>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
{% endfor %}

{% endblock %}

lib/templates/signin.html
{% extends "base.html" %}
{% block content %}

<h3 class="center-align heading-white">Sign in</h3>

<div class="row">
    <form class="col s12 m8 offset-m2" method="POST" action="{{ url_for('user.signin') }}">
        <div class="col s12 m10 offset-m1">
            <div class="card blue-grey darken-1 register-card">
                <div class="row">
                    <div class="input-field col s12">
                        <i class="fas fa-user-cog prefix"></i>
                        <input id="username" name="username" type="text" minlength="4" maxlength="18" class="validate"
                            pattern="^[a-zA-Z0-9]{4,18}$" required>
                        <label for="username">Username</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="fas fa-user-lock prefix"></i>
                        <input id="password" name="password" type="password" minlength="6" maxlength="18"
                            class="validate" pattern="^[a-zA-Z0-9]{6,18}$" required>
                        <label for="password">Password</label>
                    </div>
                </div>
                <div class="row">
                    <button type="submit" class="col s8 offset-s2 btn-large darken-4 text-shadow  teal accent-2">
                        Log in <i class="fas fa-sign-in-alt"></i>
                    </button>
                    <div class="div s2"></div>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="row">
    <div class="col-12">
        <p class="center-align">First time? <a href="{{ url_for('user.register') }}">Register here</a></p>
    </div>
</div>

{% endblock %}